### ISSUE TITLE
Render a changelog

### ISSUE THREAD

**Issue by paolobrasolin** [jonsterling/math#15]
A normal page-based feed like `jekyll-feed` offers is not very useful -- see #7 solved in #14.

Some inspiration from Gerby, which seem to generate it from git histories:
* https://kerodon.net/changes
* https://stacks.math.columbia.edu/recent-changes

TODO:
- [x] understand how Gerby does this exactly
- [x] try to reproduce it

**Comment by paolobrasolin** [comment]
Kerodon is closed source, so that's a no-go.

The changelog in [this page of Stacks](https://stacks.math.columbia.edu/recent-changes) is generated by [this template](https://github.com/gerby-project/gerby-website/blob/29f11099b25ac0acc88b29c0e689f8e9e19a4366/gerby/templates/stacks/changes.html#L27-L51) which is rendered by [this code](https://github.com/gerby-project/gerby-website/blob/29f11099b25ac0acc88b29c0e689f8e9e19a4366/gerby/views/stacks.py#L462-L469). Commits are held [in the database](https://github.com/gerby-project/gerby-website/blob/29f11099b25ac0acc88b29c0e689f8e9e19a4366/gerby/database.py#L140-L155) which is populated... somewhere? I'm still unable to find the exact location in the code.

Anyways, judging from the database schema they're relating commits from a standard `git log` with the affected nodes (which isn't trivial in their situation). In our situation nodes are separate files, so it should be much easier.

**Comment by paolobrasolin** [comment]
There's some ongoing work in #18

**Comment by jonsterling** [comment]
resolved by #18
