### ISSUE TITLE
Abandon `@include`s

### ISSUE THREAD

**Issue by paolobrasolin** [jonsterling/math#27]
I was thinking about #6 (in terms of using layouts) and I realized all the current regexp-ing is not only messy but redundant.

Consider this `0000.md`:

```
---
title: The root node
---

This is the introduction. Two sections will follow shortly.

@include{0001}

The reader will see this paragraph as belonging the last section opened in `0001`
(at whatever depth), despite being in the file for `0000`.

@include{0002}

The same goes for this paragraph, wrt `0002`. 
```

Of course you're doing nothing like this: given the hierarchical meaning we're attributing to nodes, that's definitely pathologic despite the syntax allowing for it!

To fully embrace the idea that `NODE = TEXT, NODE, NODE, NODE, ...` we can simply list the subnodes in the front matter:

```
---
title: The root node
subnodes:
  - '0001'
  - '0002'
---

This is the introduction. Two sections will follow shortly.
```

This feels cleaner and safer, but I think it will also be very helpful with tweaking the architecture for #6.

If you like the idea, here's a PR: #26 (there's also a small performance improvement).

**Comment by jonsterling** [comment]
Hmm... So my perspective was that it is desirable to be allowed to interleave these things, but I am open to the possibility that I am wrong :) I guess in my math so far I have never deviated from what it supported by your new model?

**Comment by jonsterling** [comment]
If it does help open the road toward getting #6 working, I am especially open to it.

**Comment by paolobrasolin** [comment]
> Hmm... So my perspective was that it is desirable to be allowed to interleave these things, but I am open to the possibility that I am wrong :) I guess in my math so far I have never deviated from what it supported by your new model?

I believe you're implicitly following LaTeX sectioning conventions (which in turn is what Gerby does): you never reopen a previous section.

> If it does help open the road toward getting #6 working, I am especially open to it.

I don't think it's _essential_ but I think it'll make things easier.

> it is desirable to be allowed to interleave these things

...aaand of course I just realized you're right afterall: non-section nodes like lemmas should be able to appear in the middle of their parent, see https://stacks.math.columbia.edu/tag/09HW

Uhm. So what I suggested is ok for sectioning nodes but not for "leaves" of the tree (theorems, lemmas, etc).

I'll think about this a bit more. Thanks for the input. :+1:

**Comment by jonsterling** [comment]
Perhaps it helps to say, I was imagining lemma nodes still being separate files that are imported by a parent. So it might be that the way I am envisioning using this tool is compatible with your new model.

**Comment by jonsterling** [comment]
Ah, I thought about it some more and I definitely do need the lemma nodes to appear in the middle of the parent.

**Comment by paolobrasolin** [comment]
> Ah, I thought about it some more and I definitely do need the lemma nodes to appear in the middle of the parent.

Yes! I completely agree with you now. This was a dead end, except for the node lookup optimization which is easily recovered and I'll cherry pick. :+1:
