### ISSUE TITLE
Referrers out of order

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/math#32]
I added a reference to a node and then I noticed that the referrers are being displayed in an order that was unexpected to me. Not a super high priority for me, but if it is low hanging fruit, might be good to fix.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/55057/151116642-8983e481-65ca-48b8-a492-128cc9a1d934.png">

**Comment by paolobrasolin** [comment]
I believe the order is expected (they're sorted by slug) but undesired.
I'll make them sorted them by numbering. :+1:

**Comment by jonsterling** [comment]
@paolobrasolin Ah ok cool!

**Comment by jonsterling** [comment]
Resolved by #34

**Comment by paolobrasolin** [comment]
Now that `iso_2145` is gone, this needs to be fixed again; taking care of it right now.
