### ISSUE TITLE
Definition/theorem nodes

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/math#6]
Currently there is one kind of node, basically a "subsection" node. Each of these has a heading. 

It would be nice to support alternative nodes, like Definition or Theorem. My preference at this time would be to group these under a single layout and allow the author to specify whether it is called Definition or Theorem or Conjecture or whatever, since it doesn't make sense to fix in advance all these kinds of node. We could call these "paragraph nodes" or "terminal nodes". 

The main difference between a paragraph node and a subsection node is how they are formatted. Some examples:

> [00H3] **Lemma**. Body

> [00H4] **Definition** (Optional title). Body.

**Comment by paolobrasolin** [comment]
I have a **very rough WIP** in #28, @jonsterling 

Subnode types correspond to _special_ layouts, so in theory a user can both define new ones (therorem, definition, ...) and use a single parametrized one like the one I sketched (`result`).

The branch is runnable, if you wanna take a look. There's a single corollary which I have put into its own node.

Let me know if you have any idea to improve usability! :pray: 

---

In context:

![image](https://user-images.githubusercontent.com/2499655/150411757-7ef53308-6b63-4e68-8a04-67f1d303f962.png)

---

As a standalone:

![image](https://user-images.githubusercontent.com/2499655/150411804-04488d05-1bb0-4f8b-a7e4-6097cfaf96b9.png)

**Comment by paolobrasolin** [comment]
Closing this! :confetti_ball: All details are discussed in #28.
