### ISSUE TITLE
Turn off the jekyll-feed

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/math#7]
This takes a really long time to generate, and it doesn't seem applicable. I think we cannot remove it unless we use a custom theme besides `minima`, however.

One other thing I notice is that each successive rebuild takes about .5 seconds longer than the last until I restart Jekyll. Incremental works better ~~, but this isn't fully operative with antex yet.~~ Not a huge deal, but it may become an issue later when I am trying to build more content.

**Comment by paolobrasolin** [comment]
I'm not 100% sure a working feed is completely worthless -- see https://github.com/jonsterling/math/pull/9#pullrequestreview-853707858

Perhaps a feed of _changes_ would be more useful... :thinking: I think the Stacks Project directly uses the git log!

I'll try setting a higher priority on `Sheafy`'s hook and see if it `jekyll-feed` plays along.
That's necessary for interaction with other plugins in anyways.

As for eliminating `jekyll-feed`, you're correct: it's a dependency of `minima`.
It should have a flag to turn it off, somewhere, though.

> each successive rebuild takes about .5 seconds longer than the last until I restart Jekyll

That worries me a little more. I'll look into that too.

**Comment by jonsterling** [comment]
1. I like the idea of the git log thing or something similar! that sounds really useful.

2. I did some more experimentation and I don't think that the feed is actually a serious performance bottleneck for us right now, I think I may have been getting tricked by the terminal output.

3. Re the successive rebuild time blowup, I think this is a longstanding problem with Jekyll. Some have blamed it on how the explosion of objects that get allocated during each build... In any case, the incremental mode seems to solve the problem for me --- and I was able to get this working in conjunction with `antex` by adding the `antex` directory to the `keep_files` configuration. So that's great!

**Comment by jonsterling** [comment]
So I have set the higher priority, but I noticed that nothing gets added to the feed anyway --- I suspect this is because jekyll makes feeds for posts, but not other collections. But I'm not sure. I'll leave feed stuff to you, since I think you have a clearer idea of what you want it to do than I do :)

**Comment by paolobrasolin** [comment]
`jekyll-feed` doesn't seem to be worth pursuing in this case, so I simply disabled it in #14.
A changelog of some kind still seems like a useful feature, so I opened #15.

**Comment by jonsterling** [comment]
Resolved by #14
